### ISSUE TITLE
Make mysql database name configuable

### ISSUE THREAD

**Issue by jkroepke** [PotatoSauceVFX/WhitelistSyncRewrite#1]
See title. Currently its hardcoded to whitelistSync

**Comment by rmnaderdev** [comment]
I will make changes to this today and release a version. It was on my list of things to do.

**Comment by rmnaderdev** [comment]
Added in version 1.1. This is now on [CurseForge](https://minecraft.curseforge.com/projects/whitelist-sync/files) in 1.10.2 - 1.12.2! 
Added in f249de6a68c7c725d16a03a9a983f982def98c92
