### ISSUE TITLE
Include dependecies into your jar

### ISSUE THREAD

**Issue by jkroepke** [PotatoSauceVFX/WhitelistSyncRewrite#3]
Hi,

like other mods, include the libs like mysql connection into you mod jar instead users lets them download separatly.

**Comment by rmnaderdev** [comment]
This is something I have been trying to do for a while now and haven't gotten very far with it. I was told I can use gson included with Minecraft so changes will be coming with that soon. I will continue working towards that.

**Comment by rmnaderdev** [comment]
@jkroepke This will be added in the next release. ;)
