### ISSUE TITLE
Add reconnection handling

### ISSUE THREAD

**Issue by jkroepke** [PotatoSauceVFX/WhitelistSyncRewrite#4]
If the database server was restarted, the mod has to reconnect to the database.

Error log:

```
[12:44:09] [Thread-16477/ERROR] [whitelistsync]: Error querying whitelisted players from database!
No operations allowed after connection closed.
```

**Comment by rmnaderdev** [comment]
Thank you for letting me know. I will implement a re-connect timer as well as some more enhancements probably today.
